# Workflow para Integração Contínua focado em testes unitários com Vitest e Yarn.
# Estrutura preparada para expansão com um único job e steps organizados.
# Executa testes na branch main usando Node.js 24.
name: Continuous Deployment
on:
  push:
    branches:
      - main
env:
  NODE_VERSION: '22'
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_SCOPE: gustavo-galdin-s-projects

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      # Passo 2: Configurar Node.js com a versão definida
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Passo 3: Habilitar Corepack para usar Yarn
      - name: Enable Corepack
        run: corepack enable
      # Passo 4: Instalar dependências com Yarn
      - name: Install dependencies
        run: yarn install
      # Passo 5: Executar os testes unitários via Vitest
      - name: Run unit tests
        run: yarn test
  
  build-and-deploy:
    name: Build and Deploy Vercel Preview
    needs: [unit-tests]
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.deploy.outputs.deployment-url }}
    
    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      # Passo 2: Configurar Node.js com a versão definida
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Passo 3: Habilitar Corepack para usar Yarn
      - name: Enable Corepack
        run: corepack enable
      # Passo 4: Instalar dependências com Yarn
      - name: Install dependencies
        run: yarn install

      # Passo 5: obter as configurações do vercel
      - name: Pull Vercel config
        run: |
          yarn vercel pull --yes \
          --environment=preview \
          --token=$VERCEL_TOKEN \
          --scope=$VERCEL_SCOPE

      # Passo 6: Build para o Vercel
      - name: Build Vercel
        run: yarn vercel build --token=$VERCEL_TOKEN
            
      # 7. Deploy preview no vercel
      - name: Deploy preview
        id: deploy
        run: |
          URL=$(yarn --silent vercel deploy \
          --prebuilt \
          --target=preview \
          --token=$VERCEL_TOKEN \
          --scope=$VERCEL_SCOPE)
          echo "deployment-url=$URL" >> $GITHUB_OUTPUT
          

  e2e-tests:
    name: Run E2E tests
    needs: [unit-tests, build-and-deploy]
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      # Passo 2: Configurar Node.js com a versão definida
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Passo 3: Habilitar Corepack para usar Yarn
      - name: Enable Corepack
        run: corepack enable
      # Passo 4: Instalar dependências com Yarn
      - name: Install dependencies
        run: yarn install

      # Passo 5: Obter a versão do Playwright instalada para chave do cache
      - name: Get Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('@playwright/test/package.json').version)")" >> $GITHUB_OUTPUT

      # Passo 6: Configurar cache para os navegadores do Playwright
      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}

      # Passo 7: Instalar o navegador Chromium (apenas se não estiver em cache)
      - name: Install Playwright Browser
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn playwright install chromium

      # Passo 8: Instalar dependências do sistema operacional para o Chromium
      - name: Install Playwright system dependencies
        run: yarn playwright install-deps chromium

      # Passo 9: Executar os testes de regressão
      - name: Run E2E regression Tests
        run: yarn playwright test
        env:
          BASE_URL: ${{ needs.build-and-deploy.outputs.deployment-url }} 

      # Passo 10: Relatório de testes Automatizados
      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7.0.1
        with:
          name: playwright-report
          path: playwright-report

      #Passo 11: Publicar report json do TestDino
      - name: Upload TestDino JSON
        if: ${{ !cancelled() }}
        run: npx tdpw upload ./playwright-report --token=${{ secrets.TESTDINO }}

  promote:
    name: Promote to Production
    needs: [build-and-deploy, e2e-tests]
    runs-on: ubuntu-latest
    
    steps:
      - name: Vercel promote
        run: |
          npx vercel@latest promote ${{ needs.build-and-deploy.outputs.deployment-url }} \
            --token=$VERCEL_TOKEN \
            --scope=$VERCEL_SCOPE \
            --yes